### PR TITLE
Add git clone of Keras tutorial

### PR DESCRIPTION
**Pull request by GilesStrong**
I think I did it correctly, anyway...

### CODE REVIEW

**Comment by mariojmdavid** [comment]
hi Gilles 2 comments before I approve the PR
you should modify git clone to go into the "/notebooks" dir, i.e.
git clone https://github.com/GilesStrong/ML_Tutorials.git /notebooks/ML_Tutorials
this way when you start Jupiter it will show up in the notebooks dir

but before that you should remove 250MB of data out of your github repo
github is not for holding data, you can put it someplace else where people can download

**Comment by GilesStrong** [comment]
Hi Mario, I've removed the data from the repo, and cleaned it from the history. Data is now hosted on cernbox and the script should wget it and put it int he right location.

**Review by mariojmdavid — APPROVED** [review]
hi Gilles
approved for now, but data should always be external from the docker image

**Comment by GilesStrong** [comment]
Thanks Mario. I was initially under the impression that the image should contain everything for the tutorial, since when I used it there was no internet connection within the image.
I now understand that images should be able to connect to the internet, however if I don't have a connection using the recommend installation instructions for the latest version, then it's likely that other attendees won't either.
So I think it would be best to keep it included, at least until after the tutorial, to avoid delays.

**Pull request merged**
